import type { PlaygroundEntry } from './types'

// ─── Reusable scenarios (stable team starting points) ───────────────────────

const REUSABLE: PlaygroundEntry[] = [
  {
    id: 'onboarding-test-env',
    title: 'Create test environment',
    description: 'Full-page onboarding — project setup, service picker, summary sidebar',
    category: 'onboarding',
    type: 'reusable-scenario',
    status: 'active',
    owner: 'Elena',
    reusable: true,
    tags: ['onboarding', 'service-create', 'new-user'],
    route: '/console/onboarding/test-env?scenario=onboarding-test-env',
    runtimeKey: 'onboarding-test-env',
  },
  {
    id: 'empty-state',
    title: 'Empty project',
    description: 'No services exist yet — ideal for empty states and first-time flows',
    category: 'service-creation',
    type: 'reusable-scenario',
    status: 'active',
    owner: 'Elena',
    reusable: true,
    tags: ['empty-state', 'first-time-user', 'service-create'],
    route: '/console/project/services?scenario=empty-state',
    runtimeKey: 'empty-state',
  },
  {
    id: 'existing-customer',
    title: 'Existing customer',
    description: 'Project with one MySQL service — lightweight starting point for service overview',
    category: 'existing-customers',
    type: 'reusable-scenario',
    status: 'active',
    owner: 'Elena',
    reusable: true,
    tags: ['existing-customer', 'services', 'mysql'],
    route: '/console/project/services?scenario=existing-customer',
    runtimeKey: 'existing-customer',
  },
  {
    id: 'many-services',
    title: 'Project services: mixed pricing',
    description: 'Pre-populated with 50+ services across types and pricing models',
    category: 'existing-customers',
    type: 'reusable-scenario',
    status: 'active',
    owner: 'Elena',
    reusable: true,
    tags: ['existing-customer', 'dense-fixture', 'mixed-pricing'],
    route: '/console/project/services?scenario=many-services',
    runtimeKey: 'many-services',
  },
]

// ─── Prototype scenarios (designer explorations) ─────────────────────────────

const PROTOTYPES: PlaygroundEntry[] = [
  {
    id: 'onboarding-playground',
    title: 'Playground',
    description: 'Just signed up — personal org, playground project, no services',
    category: 'onboarding',
    type: 'prototype',
    status: 'rough',
    owner: 'Elena',
    reusable: false,
    tags: ['onboarding', 'playground', 'pg-studio'],
    route: '/console/onboarding/playground?scenario=onboarding-playground',
    runtimeKey: 'onboarding-playground',
  },
  {
    id: 'first-time-user',
    title: 'First-time user',
    description: 'Alias of Empty project — onboarding state, no services',
    category: 'service-creation',
    type: 'prototype',
    status: 'active',
    owner: 'Elena',
    reusable: false,
    tags: ['first-time-user', 'empty-state'],
    route: '/console/project/services?scenario=first-time-user',
    runtimeKey: 'empty-state',
    aliasOf: 'empty-state',
  },
  {
    id: 'mysql-acu-rollout',
    title: 'Existing users – MySQL ACU rollout',
    description: 'Services list + "Introducing new pricing" modal',
    category: 'existing-customers',
    type: 'prototype',
    status: 'review-ready',
    owner: 'Elena',
    reusable: false,
    tags: ['pricing', 'acu', 'mysql', 'rollout'],
    route: '/console/project/services?scenario=mysql-acu-rollout',
    runtimeKey: 'mysql-acu-rollout',
  },
  {
    id: 'invoice-mixed-services',
    title: 'Mixed-service invoice',
    description: 'Invoice with PG, MySQL, Kafka, OpenSearch across two projects (shuffled)',
    category: 'existing-customers',
    type: 'prototype',
    status: 'active',
    owner: 'Elena',
    reusable: false,
    tags: ['billing', 'invoice', 'mixed-pricing'],
    route: '/console/billing?scenario=invoice-mixed-services',
    runtimeKey: 'invoice-mixed-services',
  },
  {
    id: 'invoice-plan-acumixed',
    title: 'Invoice: ACU + Plan — $1,612.45',
    description: 'Two projects with ACU and Plan (legacy) services, total $1,612.45',
    category: 'existing-customers',
    type: 'prototype',
    status: 'active',
    owner: 'Elena',
    reusable: false,
    tags: ['billing', 'invoice', 'acu', 'plan-pricing'],
    route: '/console/billing?scenario=invoice-plan-acumixed',
    runtimeKey: 'invoice-plan-acumixed',
  },
  {
    id: 'replica-mixed-pricing',
    title: 'Read replicas: mixed pricing',
    description: '4 MySQL primaries covering all ACU/legacy replica combos',
    category: 'existing-customers',
    type: 'prototype',
    status: 'active',
    owner: 'Elena',
    reusable: false,
    tags: ['replicas', 'pricing', 'mysql'],
    route: '/console/project/services?scenario=replica-mixed-pricing',
    runtimeKey: 'replica-mixed-pricing',
  },
  {
    id: 'free-dev-upgrade-v2',
    title: 'Free & Dev: Quick Upgrade V2',
    description: 'Same services, V2 modal with tier headers',
    category: 'pricing-upgrade',
    type: 'archived',
    status: 'archived',
    owner: 'Elena',
    reusable: false,
    tags: ['pricing', 'upgrade', 'plans'],
    route: '/console/project/services?scenario=free-dev-upgrade-v2',
    runtimeKey: 'free-dev-upgrade-v2',
  },
  {
    id: 'free-dev-upgrade-v3',
    title: 'Free & Dev: Quick Upgrade V3',
    description: 'Same services, V2 modal with Hobbyist and Startup-4 plans',
    category: 'pricing-upgrade',
    type: 'prototype',
    status: 'rough',
    owner: 'Elena',
    reusable: false,
    tags: ['pricing', 'upgrade', 'plans'],
    route: '/console/project/services?scenario=free-dev-upgrade-v3',
    runtimeKey: 'free-dev-upgrade-v3',
  },
  {
    id: 'free-dev-upgrade-v4',
    title: 'Free & Dev: Quick Upgrade V4',
    description: 'Developer + Hobbyist on AWS and GCP (europe-west-1)',
    category: 'pricing-upgrade',
    type: 'prototype',
    status: 'review-ready',
    owner: 'Elena',
    reusable: false,
    tags: ['pricing', 'upgrade', 'plans'],
    route: '/console/project/services?scenario=free-dev-upgrade-v4',
    runtimeKey: 'free-dev-upgrade-v4',
  },
  {
    id: 'deeptrace-demo',
    title: 'Service event logs',
    description: 'PostgreSQL service, Logs view',
    category: 'platform-observability',
    type: 'prototype',
    status: 'active',
    owner: 'Elena',
    reusable: false,
    tags: ['observability', 'logs', 'postgresql'],
    route: '/console/project/services/pg-deeptrace-demo?scenario=deeptrace-demo',
    runtimeKey: 'deeptrace-demo',
  },
]

export const REUSABLE_SCENARIOS = REUSABLE
export const PROTOTYPE_SCENARIOS = PROTOTYPES
